### ISSUE TITLE
SOURCE_PATH should be configurable

### ISSUE THREAD

**Issue by rndbblnn** [Throyer/migration-maven-plugin#1]
Not really an issue but it would be nice to be able to use a different SOURCE_PATH (currently hardcoded to src/main/resources/db/migration)

our current projects have the files in a different path and we cannot use this plugin unfortunately!

Thanks

**Comment by rndbblnn** [comment]
just saw the disclaimer in the README :man_facepalming:

**Comment by Throyer** [comment]
> just saw the disclaimer in the README 🤦‍♂️

No problem bro.
Someday when I have time, I intend to make this path parameterizable, or I'll try to do some way to read the custom path in the application's properties automatically
